@url = http://localhost:8080

###
POST {{url}}/v1/users
Content-Type: application/json

{
  "username": "myuser",
  "email": "myuser@example.com"
}

###
POST {{url}}/v1/users/1/playlists
Content-Type: application/json

{
  "name": "myplaylist"
}


###
POST {{url}}/v1/users/1/accounts
Content-Type: application/json

{
  "account_type": "Spotify"
}

###
POST {{url}}/v1/users/1/playlists
Content-Type: application/json

{
  "name": "playlist1"
}

###
GET {{url}}/v1/users

###
GET {{url}}/v1/users/1/accounts

###
GET {{url}}/v1/users/1/playlists

###
GET {{url}}/v1/users/1/playlists/1/service_playlist