@url = http://localhost:8080
@playlist_id = 1
@user_id = 1

###
GET {{url}}/ping

###
GET {{url}}/v1/users/{{user_id}}/playlists

###
GET {{url}}/v1/users/{{user_id}}/playlists/{{playlist_id}}

###
POST {{url}}/v1/users/{{user_id}}/playlists
Content-Type: application/json

{
  "name": "playlist1"
}

###
PUT {{url}}/v1/playlists/{{id}}
Content-Type: application/json

{
  "title": "test-title1",
  "isrc": "test-isrc2",
  "artist_id": 1
}

###
DELETE  {{url}}/v1/playlists/{{id}}
