@url = http://localhost:8080
@id = 1

###
GET {{url}}/ping

###
GET {{url}}/v1/tracks

###
GET {{url}}/v1/tracks/{{id}}

###
POST {{url}}/v1/tracks
Content-Type: application/json

{
  "title": "title1",
  "isrc": "isrc1",
  "artist": "artist1"
}

###
PUT {{url}}/v1/tracks/{{id}}
Content-Type: application/json

{
  "title": "title1",
  "isrc": "isrc1",
  "artist_id": 1
}

###
DELETE  {{url}}/v1/tracks/{{id}}
