@url = http://localhost:8080
@id = 1

###
GET {{url}}/ping

###
GET {{url}}/v1/users


###
GET {{url}}/v1/users/{{id}}

###
POST {{url}}/v1/users
Content-Type: application/json

{
  "username": "test",
  "email": "test email"
}

###
PUT {{url}}/v1/users/{{id}}
Content-Type: application/json

{
  "title": "test-title1",
  "isrc": "test-isrc2",
  "artist_id": 1
}

###
DELETE  {{url}}/v1/users/{{id}}
